# Generated by Django 6.0.5 on 2026-05-10 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Size name')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name product')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='Slug product')),
                ('color', models.CharField(max_length=100, verbose_name='Color product')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price product')),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('main_image', models.ImageField(upload_to='products/main/', verbose_name='Image product')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at product')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at product')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.category', verbose_name='Category product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/extra/', verbose_name='Image productimage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.product', verbose_name='Product productimage')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock productsize')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sizes', to='main.product', verbose_name='Product productsize')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_products', to='main.size', verbose_name='Size productsize')),
            ],
        ),
    ]
